import productOil from "../../assets/images/product-oil.png";
import productRice from "../../assets/images/product-rice.png";
import productWater from "../../assets/images/product-water.png";
import productTissues from "../../assets/images/product-tissues.png";

export const storeProductSummary = [
  {
    id: "purchases",
    label: "إجمالي المشتريات",
    value: "18,450 ₪",
    helper: "+12% عن الشهر الماضي",
    tone: "navy",
  },
  {
    id: "products",
    label: "إجمالي المنتجات",
    value: "1,248",
    helper: "+18% عن الشهر الماضي",
    tone: "green",
  },
  {
    id: "out-of-stock",
    label: "نفذ المخزون",
    value: "86",
    helper: "منتج غير متوفر حالياً",
    tone: "cyan",
  },
  {
    id: "popular",
    label: "الأكثر طلباً",
    value: "540",
    helper: "وحدة مطلوبة",
    tone: "orange",
  },
];

export const storeProductCategories = [
  "أغذية أساسية",
  "زيوت",
  "مشروبات",
  "معلبات",
  "مستلزمات",
];

export const storeStockStatuses = [
  "متوفر",
  "مخزون منخفض",
  "نفذ المخزون",
];

export const storeProducts = [
  {
    id: 1,
    name: "أرز بسمتي هندي",
    sku: "RICE-IND-01",
    supplier: "شركة الموارد الغذائية",
    category: "أغذية أساسية",
    price: 85,
    availableQuantity: 150,
    stockUnit: "كجم",
    stockStatus: "متوفر",
    image: productRice,
  },
  {
    id: 2,
    name: "زيت دوار الشمس 1.8 لتر",
    sku: "OIL-SUN-18",
    supplier: "الوطنية للزيوت",
    category: "زيوت",
    price: 16.5,
    availableQuantity: 42,
    stockUnit: "عبوة",
    stockStatus: "متوفر",
    image: productOil,
  },
  {
    id: 3,
    name: "سكر ناعم",
    sku: "SUG-WHT-10",
    supplier: "مصنع السكر العربي",
    category: "أغذية أساسية",
    price: 48,
    availableQuantity: 12,
    stockUnit: "كيس",
    stockStatus: "مخزون منخفض",
    image: productRice,
  },
  {
    id: 4,
    name: "مياه شرب 330 مل × 40",
    sku: "WTR-NAQ-40",
    supplier: "مياه نقي",
    category: "مشروبات",
    price: 15,
    availableQuantity: 0,
    stockUnit: "كرتونة",
    stockStatus: "نفذ المخزون",
    image: productWater,
  },
  {
    id: 5,
    name: "مكرونة سباغيتي",
    sku: "PST-SPG-01",
    supplier: "شركة المطاحن",
    category: "أغذية أساسية",
    price: 3.25,
    availableQuantity: 200,
    stockUnit: "وحدة",
    stockStatus: "متوفر",
    image: productRice,
  },
  {
    id: 6,
    name: "دقيق فاخر 10 كجم",
    sku: "FLR-PRM-10",
    supplier: "شركة الموارد الغذائية",
    category: "أغذية أساسية",
    price: 22,
    availableQuantity: 8,
    stockUnit: "وحدات",
    stockStatus: "مخزون منخفض",
    image: productRice,
  },
  {
    id: 7,
    name: "صلصة طماطم كرتون",
    sku: "TOM-PST-CRT",
    supplier: "الواحة الغذائية",
    category: "معلبات",
    price: 58,
    availableQuantity: 55,
    stockUnit: "وحدة",
    stockStatus: "متوفر",
    image: productTissues,
  },
  {
    id: 8,
    name: "شاي كيس 100 حبة",
    sku: "TEA-KBS-100",
    supplier: "شركة الموارد الغذائية",
    category: "مشروبات",
    price: 12.5,
    availableQuantity: 90,
    stockUnit: "وحدة",
    stockStatus: "متوفر",
    image: productTissues,
  },
  {
    id: 9,
    name: "زيت ذرة 1.5 لتر",
    sku: "OIL-CRN-15",
    supplier: "الوطنية للزيوت",
    category: "زيوت",
    price: 15.75,
    availableQuantity: 31,
    stockUnit: "عبوة",
    stockStatus: "متوفر",
    image: productOil,
  },
  {
    id: 10,
    name: "مياه معدنية 1.5 لتر × 12",
    sku: "WTR-MIN-12",
    supplier: "الخليج للتجارة",
    category: "مشروبات",
    price: 18,
    availableQuantity: 20,
    stockUnit: "كرتونة",
    stockStatus: "متوفر",
    image: productWater,
  },
  {
    id: 11,
    name: "أرز مصري 5 كجم",
    sku: "RICE-EGY-05",
    supplier: "مؤسسة النور للتجارة",
    category: "أغذية أساسية",
    price: 34,
    availableQuantity: 9,
    stockUnit: "كيس",
    stockStatus: "مخزون منخفض",
    image: productRice,
  },
  {
    id: 12,
    name: "تونة قطع 185 جم",
    sku: "TUNA-185-24",
    supplier: "شركة الصافي",
    category: "معلبات",
    price: 46,
    availableQuantity: 64,
    stockUnit: "كرتونة",
    stockStatus: "متوفر",
    image: productTissues,
  },
  {
    id: 13,
    name: "حمص حب معلب",
    sku: "CHP-CAN-24",
    supplier: "الواحة الغذائية",
    category: "معلبات",
    price: 37.5,
    availableQuantity: 0,
    stockUnit: "كرتونة",
    stockStatus: "نفذ المخزون",
    image: productTissues,
  },
  {
    id: 14,
    name: "مناديل ورقية 200 منديل",
    sku: "TIS-200-12",
    supplier: "مؤسسة التموين",
    category: "مستلزمات",
    price: 10.25,
    availableQuantity: 75,
    stockUnit: "عبوة",
    stockStatus: "متوفر",
    image: productTissues,
  },
  {
    id: 15,
    name: "أكواب ورقية 12 أونصة",
    sku: "CUP-12OZ-50",
    supplier: "مؤسسة التموين",
    category: "مستلزمات",
    price: 11,
    availableQuantity: 14,
    stockUnit: "رزمة",
    stockStatus: "مخزون منخفض",
    image: productTissues,
  },
  {
    id: 16,
    name: "عصير برتقال 1 لتر",
    sku: "JCE-ORG-01",
    supplier: "شركة المدينة",
    category: "مشروبات",
    price: 9.5,
    availableQuantity: 80,
    stockUnit: "كرتونة",
    stockStatus: "متوفر",
    image: productWater,
  },
  {
    id: 17,
    name: "سكر أبيض 1 كجم",
    sku: "SUG-WHT-01",
    supplier: "مصنع السكر العربي",
    category: "أغذية أساسية",
    price: 6.75,
    availableQuantity: 110,
    stockUnit: "كيس",
    stockStatus: "متوفر",
    image: productRice,
  },
  {
    id: 18,
    name: "زيت نباتي 3 لتر",
    sku: "OIL-VEG-03",
    supplier: "الوطنية للزيوت",
    category: "زيوت",
    price: 27.5,
    availableQuantity: 6,
    stockUnit: "عبوة",
    stockStatus: "مخزون منخفض",
    image: productOil,
  },
  {
    id: 19,
    name: "فول مدمس معلب",
    sku: "BEAN-CAN-24",
    supplier: "الواحة الغذائية",
    category: "معلبات",
    price: 35,
    availableQuantity: 45,
    stockUnit: "كرتونة",
    stockStatus: "متوفر",
    image: productTissues,
  },
  {
    id: 20,
    name: "مياه شرب 500 مل × 24",
    sku: "WTR-500-24",
    supplier: "مياه نقي",
    category: "مشروبات",
    price: 13.5,
    availableQuantity: 0,
    stockUnit: "كرتونة",
    stockStatus: "نفذ المخزون",
    image: productWater,
  },
  {
    id: 21,
    name: "ملح طعام 1 كجم",
    sku: "SALT-01KG",
    supplier: "شركة المطاحن",
    category: "أغذية أساسية",
    price: 3,
    availableQuantity: 130,
    stockUnit: "كيس",
    stockStatus: "متوفر",
    image: productRice,
  },
  {
    id: 22,
    name: "أكياس تسوق كبيرة",
    sku: "BAG-LRG-100",
    supplier: "مؤسسة التموين",
    category: "مستلزمات",
    price: 8.5,
    availableQuantity: 33,
    stockUnit: "رزمة",
    stockStatus: "متوفر",
    image: productTissues,
  },
  {
    id: 23,
    name: "ذرة حلوة معلبة",
    sku: "CORN-CAN-24",
    supplier: "شركة الصافي",
    category: "معلبات",
    price: 39,
    availableQuantity: 10,
    stockUnit: "كرتونة",
    stockStatus: "مخزون منخفض",
    image: productTissues,
  },
  {
    id: 24,
    name: "عصير تفاح 1 لتر",
    sku: "JCE-APL-01",
    supplier: "شركة المدينة",
    category: "مشروبات",
    price: 9.75,
    availableQuantity: 68,
    stockUnit: "كرتونة",
    stockStatus: "متوفر",
    image: productWater,
  },
];