import productOil from "../../assets/images/product-oil.png";
import productRice from "../../assets/images/product-rice.png";
import productWater from "../../assets/images/product-water.png";
import productTissues from "../../assets/images/product-tissues.png";

export const storeOrderSummary = [
  {
    id: "all",
    label: "إجمالي الطلبات",
    value: 38,
    helper: "هذا الشهر",
    tone: "blue",
  },
  {
    id: "processing",
    label: "قيد المعالجة",
    value: 12,
    helper: "طلبات قيد التنفيذ",
    tone: "orange",
  },
  {
    id: "delivered",
    label: "تم التسليم",
    value: 21,
    helper: "تم التسليم بنجاح",
    tone: "green",
  },
  {
    id: "cancelled",
    label: "الملغاة",
    value: 5,
    helper: "طلبات ملغاة",
    tone: "red",
  },
];

export const storeOrderStatusOptions = [
  "جديد",
  "قيد التجهيز",
  "قيد الشحن",
  "تم التسليم",
];

export const currentStoreOrders = [
  {
    id: 10245,
    orderNumber: "#ORD-10245",
    supplier: "شركة الموارد الغذائية",
    supplierInitial: "م",
    supplierClass: "bg-[#6B63D9]",
    date: "2026-08-17",
    dateLabel: "17 أغسطس 2026",
    timeLabel: "10:30 ص",
    status: "جديد",
    paymentStatus: "غير مدفوع",
    deliveryAddress: "غزة - حي الرمال - شارع الوحدة",
    items: [
      {
        productId: 1,
        name: "أرز بسمتي هندي",
        sku: "RICE-IND-01",
        quantity: 2,
        unitPrice: 85,
        image: productRice,
      },
      {
        productId: 6,
        name: "دقيق فاخر 10 كجم",
        sku: "FLR-PRM-10",
        quantity: 1,
        unitPrice: 22,
        image: productRice,
      },
      {
        productId: 8,
        name: "شاي كيس 100 حبة",
        sku: "TEA-KBS-100",
        quantity: 2,
        unitPrice: 12.5,
        image: productTissues,
      },
    ],
  },
  {
    id: 10244,
    orderNumber: "#ORD-10244",
    supplier: "الوطنية للزيوت",
    supplierInitial: "و",
    supplierClass: "bg-[#19A974]",
    date: "2026-08-16",
    dateLabel: "16 أغسطس 2026",
    timeLabel: "02:15 م",
    status: "قيد التجهيز",
    paymentStatus: "مدفوع",
    deliveryAddress: "غزة - تل الهوى - شارع الصناعة",
    items: [
      {
        productId: 2,
        name: "زيت دوار الشمس 1.8 لتر",
        sku: "OIL-SUN-18",
        quantity: 4,
        unitPrice: 16.5,
        image: productOil,
      },
      {
        productId: 9,
        name: "زيت ذرة 1.5 لتر",
        sku: "OIL-CRN-15",
        quantity: 3,
        unitPrice: 15.75,
        image: productOil,
      },
      {
        productId: 18,
        name: "زيت نباتي 3 لتر",
        sku: "OIL-VEG-03",
        quantity: 1,
        unitPrice: 27.5,
        image: productOil,
      },
    ],
  },
  {
    id: 10243,
    orderNumber: "#ORD-10243",
    supplier: "مؤسسة التموين",
    supplierInitial: "ت",
    supplierClass: "bg-[#3B82F6]",
    date: "2026-08-15",
    dateLabel: "15 أغسطس 2026",
    timeLabel: "09:45 ص",
    status: "قيد الشحن",
    paymentStatus: "مدفوع",
    deliveryAddress: "خانيونس - وسط البلد - شارع البحر",
    items: [
      {
        productId: 14,
        name: "مناديل ورقية 200 منديل",
        sku: "TIS-200-12",
        quantity: 4,
        unitPrice: 10.25,
        image: productTissues,
      },
      {
        productId: 15,
        name: "أكواب ورقية 12 أونصة",
        sku: "CUP-12OZ-50",
        quantity: 2,
        unitPrice: 11,
        image: productTissues,
      },
      {
        productId: 22,
        name: "أكياس تسوق كبيرة",
        sku: "BAG-LRG-100",
        quantity: 3,
        unitPrice: 8.5,
        image: productTissues,
      },
    ],
  },
  {
    id: 10242,
    orderNumber: "#ORD-10242",
    supplier: "شركة المدينة",
    supplierInitial: "م",
    supplierClass: "bg-[#FF8736]",
    date: "2026-08-14",
    dateLabel: "14 أغسطس 2026",
    timeLabel: "11:20 ص",
    status: "تم التسليم",
    paymentStatus: "مدفوع",
    deliveryAddress: "دير البلح - شارع السوق",
    items: [
      {
        productId: 16,
        name: "عصير برتقال 1 لتر",
        sku: "JCE-ORG-01",
        quantity: 5,
        unitPrice: 9.5,
        image: productWater,
      },
      {
        productId: 24,
        name: "عصير تفاح 1 لتر",
        sku: "JCE-APL-01",
        quantity: 5,
        unitPrice: 9.75,
        image: productWater,
      },
    ],
  },
  {
    id: 10241,
    orderNumber: "#ORD-10241",
    supplier: "الواحة الغذائية",
    supplierInitial: "و",
    supplierClass: "bg-[#8B5CF6]",
    date: "2026-08-13",
    dateLabel: "13 أغسطس 2026",
    timeLabel: "01:05 م",
    status: "قيد التجهيز",
    paymentStatus: "مدفوع",
    deliveryAddress: "غزة - الشجاعية - شارع بغداد",
    items: [
      {
        productId: 7,
        name: "صلصة طماطم كرتون",
        sku: "TOM-PST-CRT",
        quantity: 2,
        unitPrice: 58,
        image: productTissues,
      },
      {
        productId: 19,
        name: "فول مدمس معلب",
        sku: "BEAN-CAN-24",
        quantity: 2,
        unitPrice: 35,
        image: productTissues,
      },
    ],
  },
  {
    id: 10240,
    orderNumber: "#ORD-10240",
    supplier: "شركة الصافي",
    supplierInitial: "ص",
    supplierClass: "bg-[#0EA5A4]",
    date: "2026-08-12",
    dateLabel: "12 أغسطس 2026",
    timeLabel: "08:40 ص",
    status: "جديد",
    paymentStatus: "غير مدفوع",
    deliveryAddress: "رفح - حي الجنينة",
    items: [
      {
        productId: 12,
        name: "تونة قطع 185 جم",
        sku: "TUNA-185-24",
        quantity: 2,
        unitPrice: 46,
        image: productTissues,
      },
      {
        productId: 23,
        name: "ذرة حلوة معلبة",
        sku: "CORN-CAN-24",
        quantity: 2,
        unitPrice: 39,
        image: productTissues,
      },
    ],
  },
];

export const previousStoreOrders = [
  {
    id: 10239,
    orderNumber: "#ORD-10239",
    supplier: "شركة الموارد الغذائية",
    supplierInitial: "م",
    supplierClass: "bg-[#6B63D9]",
    date: "2026-07-13",
    dateLabel: "13 يوليو 2026",
    timeLabel: "12:10 م",
    status: "تم التسليم",
    paymentStatus: "مدفوع",
    deliveryAddress: "غزة - حي الرمال - شارع الوحدة",
    items: [
      {
        productId: 1,
        name: "أرز بسمتي هندي",
        sku: "RICE-IND-01",
        quantity: 1,
        unitPrice: 82,
        image: productRice,
      },
      {
        productId: 8,
        name: "شاي كيس 100 حبة",
        sku: "TEA-KBS-100",
        quantity: 2,
        unitPrice: 12,
        image: productTissues,
      },
    ],
  },
  {
    id: 10238,
    orderNumber: "#ORD-10238",
    supplier: "الوطنية للزيوت",
    supplierInitial: "و",
    supplierClass: "bg-[#19A974]",
    date: "2026-07-12",
    dateLabel: "12 يوليو 2026",
    timeLabel: "03:25 م",
    status: "تم التسليم",
    paymentStatus: "مدفوع",
    deliveryAddress: "غزة - تل الهوى - شارع الصناعة",
    items: [
      {
        productId: 2,
        name: "زيت دوار الشمس 1.8 لتر",
        sku: "OIL-SUN-18",
        quantity: 3,
        unitPrice: 15.75,
        image: productOil,
      },
      {
        productId: 9,
        name: "زيت ذرة 1.5 لتر",
        sku: "OIL-CRN-15",
        quantity: 2,
        unitPrice: 15,
        image: productOil,
      },
    ],
  },
  {
    id: 10237,
    orderNumber: "#ORD-10237",
    supplier: "مؤسسة التموين",
    supplierInitial: "ت",
    supplierClass: "bg-[#3B82F6]",
    date: "2026-07-11",
    dateLabel: "11 يوليو 2026",
    timeLabel: "10:05 ص",
    status: "تم التسليم",
    paymentStatus: "مدفوع",
    deliveryAddress: "خانيونس - وسط البلد - شارع البحر",
    items: [
      {
        productId: 14,
        name: "مناديل ورقية 200 منديل",
        sku: "TIS-200-12",
        quantity: 4,
        unitPrice: 9.75,
        image: productTissues,
      },
      {
        productId: 15,
        name: "أكواب ورقية 12 أونصة",
        sku: "CUP-12OZ-50",
        quantity: 4,
        unitPrice: 10.5,
        image: productTissues,
      },
    ],
  },
  {
    id: 10236,
    orderNumber: "#ORD-10236",
    supplier: "شركة المدينة",
    supplierInitial: "م",
    supplierClass: "bg-[#FF8736]",
    date: "2026-06-28",
    dateLabel: "28 يونيو 2026",
    timeLabel: "04:00 م",
    status: "تم التسليم",
    paymentStatus: "مدفوع",
    deliveryAddress: "دير البلح - شارع السوق",
    items: [
      {
        productId: 16,
        name: "عصير برتقال 1 لتر",
        sku: "JCE-ORG-01",
        quantity: 6,
        unitPrice: 9,
        image: productWater,
      },
      {
        productId: 24,
        name: "عصير تفاح 1 لتر",
        sku: "JCE-APL-01",
        quantity: 4,
        unitPrice: 9.25,
        image: productWater,
      },
    ],
  },
  {
    id: 10235,
    orderNumber: "#ORD-10235",
    supplier: "مصنع السكر العربي",
    supplierInitial: "س",
    supplierClass: "bg-[#A16207]",
    date: "2026-06-20",
    dateLabel: "20 يونيو 2026",
    timeLabel: "09:15 ص",
    status: "تم التسليم",
    paymentStatus: "مدفوع",
    deliveryAddress: "غزة - حي النصر",
    items: [
      {
        productId: 3,
        name: "سكر ناعم",
        sku: "SUG-WHT-10",
        quantity: 2,
        unitPrice: 46,
        image: productRice,
      },
      {
        productId: 17,
        name: "سكر أبيض 1 كجم",
        sku: "SUG-WHT-01",
        quantity: 5,
        unitPrice: 6.25,
        image: productRice,
      },
    ],
  },
];