export const storeSuppliers = [
  {
    id: 1,
    name: "شركة موسى حميد",
    shortName: "م",
    description: "مورد مواد غذائية",
    location: "غزة",
    avatarClass: "bg-[#5B69C5]",
  },
  {
    id: 2,
    name: "شركة الصافي",
    shortName: "ص",
    description: "مورد منظفات وتغليف",
    location: "خانيونس",
    avatarClass: "bg-[#36965D]",
  },
  {
    id: 3,
    name: "شركة خيار الشنطي",
    shortName: "خ",
    description: "لتجارة الخضار والفواكه",
    location: "دير البلح",
    avatarClass: "bg-[#2569B9]",
  },
  {
    id: 4,
    name: "شركة المدينة",
    shortName: "م",
    description: "للمشروبات والعصائر",
    location: "رفح",
    avatarClass: "bg-[#F97316]",
  },
  {
    id: 5,
    name: "مؤسسة النور للتجارة",
    shortName: "ن",
    description: "مورد مواد غذائية وتموينية",
    location: "غزة",
    avatarClass: "bg-[#40577B]",
  },
  {
    id: 6,
    name: "شركة عهد العالمية",
    shortName: "ع",
    description: "مورد حبوب ومواد غذائية",
    location: "النصيرات",
    avatarClass: "bg-[#6D4FB3]",
  },
  {
    id: 7,
    name: "الخليج للتجارة",
    shortName: "خ",
    description: "مورد مياه ومشروبات",
    location: "المغازي",
    avatarClass: "bg-[#0B7890]",
  },
  {
    id: 8,
    name: "مؤسسة التموين",
    shortName: "ت",
    description: "مورد مستلزمات ومنتجات ورقية",
    location: "غزة",
    avatarClass: "bg-[#9A6C00]",
  },
  {
    id: 9,
    name: "شركة الأمانة للتوزيع",
    shortName: "أ",
    description: "مورد مواد غذائية",
    location: "خانيونس",
    avatarClass: "bg-[#16834B]",
  },
  {
    id: 10,
    name: "مؤسسة الوفاء",
    shortName: "و",
    description: "مورد منظفات ومستلزمات",
    location: "دير البلح",
    avatarClass: "bg-[#A84B08]",
  },
  {
    id: 11,
    name: "شركة البركة التجارية",
    shortName: "ب",
    description: "مورد أغذية ومشروبات",
    location: "النصيرات",
    avatarClass: "bg-[#3B82F6]",
  },
  {
    id: 12,
    name: "مؤسسة السلام",
    shortName: "س",
    description: "مورد تغليف ومستلزمات متاجر",
    location: "رفح",
    avatarClass: "bg-[#7C3AED]",
  },
];